//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardobeClient.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/WardobeLibrary.WCFClasses")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IAccountContract")]
    public interface IAccountContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Login", ReplyAction="http://tempuri.org/IAccountContract/LoginResponse")]
        string Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Login", ReplyAction="http://tempuri.org/IAccountContract/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Register", ReplyAction="http://tempuri.org/IAccountContract/RegisterResponse")]
        bool Register(WardobeClient.Proxy.Account account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Register", ReplyAction="http://tempuri.org/IAccountContract/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(WardobeClient.Proxy.Account account, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/GetInfo", ReplyAction="http://tempuri.org/IAccountContract/GetInfoResponse")]
        WardobeClient.Proxy.Account GetInfo(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/GetInfo", ReplyAction="http://tempuri.org/IAccountContract/GetInfoResponse")]
        System.Threading.Tasks.Task<WardobeClient.Proxy.Account> GetInfoAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Disconnect", ReplyAction="http://tempuri.org/IAccountContract/DisconnectResponse")]
        void Disconnect(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountContract/Disconnect", ReplyAction="http://tempuri.org/IAccountContract/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountContractChannel : WardobeClient.Proxy.IAccountContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountContractClient : System.ServiceModel.ClientBase<WardobeClient.Proxy.IAccountContract>, WardobeClient.Proxy.IAccountContract {
        
        public AccountContractClient() {
        }
        
        public AccountContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
        
        public bool Register(WardobeClient.Proxy.Account account, string password) {
            return base.Channel.Register(account, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(WardobeClient.Proxy.Account account, string password) {
            return base.Channel.RegisterAsync(account, password);
        }
        
        public WardobeClient.Proxy.Account GetInfo(string token) {
            return base.Channel.GetInfo(token);
        }
        
        public System.Threading.Tasks.Task<WardobeClient.Proxy.Account> GetInfoAsync(string token) {
            return base.Channel.GetInfoAsync(token);
        }
        
        public void Disconnect(string token) {
            base.Channel.Disconnect(token);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string token) {
            return base.Channel.DisconnectAsync(token);
        }
    }
}
