// <auto-generated />
namespace WardobeLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ReworkingallthatdonotworkingAddingnewclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReworkingallthatdonotworkingAddingnewclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131812334_Reworking all that do not working. Adding new class."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
