// <auto-generated />
namespace WardobeLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RenamingCurrenttoDailyNowweatherisforeachhournotforcurrenttime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamingCurrenttoDailyNowweatherisforeachhournotforcurrenttime));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131832416_Renaming Current to Daily. Now weather is for each hour, not for current time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
